---

-  hosts: all
   become: true
   pre_tasks:

     -  name: Install Updates (Ubuntu)
        apt:
          upgrade: dist
          update_cache: yes
        when: ansible_distribution == "Ubuntu"

     -  name: Install updates (CentOS)
        yum:
          update_only: yes
          update_cache: yes
        when: ansible_distribution == "CentOS"

-  hosts: Ubuntu
   become: true
   tasks:

     -  name: Install UFW (Uncomplicated Firewall)
        apt:
          name: ufw
          state: present

     -  name: Enable UFW
        community.general.ufw:
          state: enabled
          policy: allow

     -  name: Allowing OpenSSH with UFW
        community.general.ufw:
          rule: allow
          name: OpenSSH

     -  name: Allow access to TCP Port 80
        community.general.ufw:
          rule: allow
          port: '80'
          proto: tcp

-  hosts: CentOS
   become: true
   tasks:

     -  name: Install Firewalld
        yum:
          name: firewalld
          state: present

     -  name: Enabling Firewall with SystemMD
        systemd:
          name: firewalld
          state: started
          enabled: true

     -  name: Permit OpenSSH
        ansible.posix.firewalld:
          service: ssh
          permanent: true
          state: enabled

     -  name: Allow access to TCP Port 80
        ansible.posix.firewalld:
          port: 80/tcp
          permanent: true
          state: enabled

     -  name: Reload Firewalld
        shell: firewall-cmd --reload
